
import { Word, ShopItem, Achievement, Sugia } from './types';

export const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycby2j8DTeve82fE_a_4j1_Py3SZj02JlrroBWzONc_Mtk1X7VVIbUHpKpdtvWgjqS15l4w/exec';

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'zurba', title: 'מאסטר קומבו', desc: 'רצף (Combo) של 10 פגיעות נכונות ברצף', icon: '🎯' },
  { id: 'sinai', title: 'ריצה מושלמת', desc: 'ניצחון על בוס בלי לאבד אף חיים', icon: '⭐' },
  { id: 'gamir', title: 'אספן ציוד', desc: 'רכישת כל השדרוגים והסקינים בחנות', icon: '🧰' }
];

export const SUGIOT: Sugia[] = [
  { id: 0, title: 'יחידה 1: חימום', location: 'nehardea', description: 'חימום קצר – האויבים נעים בתנועה גלית.', requiredLevel: 1, modifier: 'wave' },
  { id: 1, title: 'יחידה 2: פוקוס', location: 'nehardea', description: 'יותר עומס – צפיפות אויבים גדולה יותר.', requiredLevel: 8, modifier: 'density' },
  { id: 2, title: 'יחידה 3: מטר אותיות', location: 'sura', description: 'זהירות! אותיות נופלות מהשמיים.', requiredLevel: 15, modifier: 'hazards' },
  { id: 3, title: 'יחידה 4: מהירות', location: 'sura', description: 'האויבים מאיצים לקראתך – צריך תגובה מהירה.', requiredLevel: 22, modifier: 'accelerate' },
  { id: 4, title: 'יחידה 5: מיקרו-מילים', location: 'pumbedita', description: 'מילים קטנות ומהירות במיוחד.', requiredLevel: 29, modifier: 'sharpness' },
  { id: 5, title: 'יחידה 6: רוח צד', location: 'pumbedita', description: 'רוח צדדית משפיעה על תנועת המטוס.', requiredLevel: 36, modifier: 'drift' },
  { id: 6, title: 'יחידה 7: הבהוב', location: 'mahoza', description: 'האויבים מהבהבים ונעלמים מהעין.', requiredLevel: 43, modifier: 'blink' },
  { id: 7, title: 'יחידה 8: כאוס', location: 'mahoza', description: 'מסלולים קופצניים ולא צפויים.', requiredLevel: 50, modifier: 'chaos' },
  { id: 8, title: 'יחידה 9: חושך', location: 'matamehasia', description: 'הראות מוגבלת לאזור הקרוב למטוס.', requiredLevel: 57, modifier: 'darkness' },
  { id: 9, title: 'יחידה 10: מערבולת', location: 'matamehasia', description: 'האויבים נמשכים למרכז המסך.', requiredLevel: 64, modifier: 'vortex' },
  { id: 10, title: 'יחידה 11: סערה', location: 'beiradelvat', description: 'רוחות חזקות ומכשולים רבים.', requiredLevel: 71, modifier: 'storm' },
  { id: 11, title: 'יחידה 12: מבחן סופי', location: 'beiradelvat', description: 'שילוב כל האתגרים לקרב האחרון.', requiredLevel: 78, modifier: 'final' }
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'skin_default', name: 'מטוס רגיל', type: 'skin', price: 0, desc: 'מטוס קרב סטנדרטי שיורה כדורי אנרגיה', icon: '✈️' },
  { id: 'skin_gold', name: 'סילון זהב', type: 'skin', price: 800, desc: 'מטוס יוקרתי שיורה קרן אור עוצמתית (דרוש מאסטר קומבו)', icon: '☀️', requiredAchievement: 'zurba' },
  { id: 'skin_butzina', name: 'לייזר סגול', type: 'skin', price: 1000, desc: 'מטוס בצבע סגול שיורה קווי לייזר', icon: '🟣' },
  { id: 'skin_torah', name: 'תותח אש', type: 'skin', price: 1500, desc: 'מטוס עם ירי אש עוצמתי (דרושה ריצה מושלמת)', icon: '🔥', requiredAchievement: 'sinai' },
  { id: 'skin_choshen', name: 'קשת חשמל', type: 'skin', price: 2000, desc: 'מבנה עוצמתי שיורה קשתות חשמל', icon: '⚡' },
  { id: 'upgrade_bomb', name: 'פצצת איפוס', type: 'consumable', price: 250, desc: 'מנקה את כל המסך מאויבים', icon: '💣' },
  { id: 'item_shield', name: 'מגן אנרגיה', type: 'consumable', price: 300, desc: 'מגן מפני פגיעה אחת (לחץ S) - עד 3', icon: '🛡️' },
  { id: 'item_freeze', name: 'האטת זמן', type: 'consumable', price: 400, desc: 'מאט את כל האויבים לזמן ממושך (לחץ D) - עד 3', icon: '⏳' }
];

export const DICTIONARY: Word[] = [
    // בסיס (Common)
    { aramaic: "hello", hebrew: "שלום", cat: "common" },
    { aramaic: "goodbye", hebrew: "להתראות", cat: "common" },
    { aramaic: "please", hebrew: "בבקשה", cat: "common" },
    { aramaic: "thank you", hebrew: "תודה", cat: "common" },
    { aramaic: "sorry", hebrew: "סליחה", cat: "common" },
    { aramaic: "yes", hebrew: "כן", cat: "common" },
    { aramaic: "no", hebrew: "לא", cat: "common" },
    { aramaic: "maybe", hebrew: "אולי", cat: "common" },
    { aramaic: "now", hebrew: "עכשיו", cat: "common" },
    { aramaic: "later", hebrew: "אחר כך", cat: "common" },
    { aramaic: "today", hebrew: "היום", cat: "common" },
    { aramaic: "tomorrow", hebrew: "מחר", cat: "common" },
    { aramaic: "yesterday", hebrew: "אתמול", cat: "common" },
    { aramaic: "always", hebrew: "תמיד", cat: "common" },
    { aramaic: "never", hebrew: "אף פעם", cat: "common" },
    { aramaic: "sometimes", hebrew: "לפעמים", cat: "common" },
    { aramaic: "again", hebrew: "שוב", cat: "common" },
    { aramaic: "because", hebrew: "בגלל", cat: "common" },
    { aramaic: "but", hebrew: "אבל", cat: "common" },
    { aramaic: "and", hebrew: "וגם", cat: "common" },
    { aramaic: "or", hebrew: "או", cat: "common" },
    { aramaic: "who", hebrew: "מי", cat: "common" },
    { aramaic: "what", hebrew: "מה", cat: "common" },
    { aramaic: "where", hebrew: "איפה", cat: "common" },
    { aramaic: "when", hebrew: "מתי", cat: "common" },
    { aramaic: "why", hebrew: "למה", cat: "common" },
    { aramaic: "how", hebrew: "איך", cat: "common" },
    { aramaic: "big", hebrew: "גדול", cat: "common" },
    { aramaic: "small", hebrew: "קטן", cat: "common" },
    { aramaic: "good", hebrew: "טוב", cat: "common" },
    { aramaic: "bad", hebrew: "רע", cat: "common" },
    { aramaic: "new", hebrew: "חדש", cat: "common" },
    { aramaic: "old", hebrew: "ישן", cat: "common" },
    { aramaic: "hot", hebrew: "חם", cat: "common" },
    { aramaic: "cold", hebrew: "קר", cat: "common" },
    { aramaic: "fast", hebrew: "מהיר", cat: "common" },
    { aramaic: "slow", hebrew: "איטי", cat: "common" },
    { aramaic: "easy", hebrew: "קל", cat: "common" },
    { aramaic: "hard", hebrew: "קשה", cat: "common" },
    { aramaic: "happy", hebrew: "שמח", cat: "common" },
    { aramaic: "sad", hebrew: "עצוב", cat: "common" },
    { aramaic: "strong", hebrew: "חזק", cat: "common" },
    { aramaic: "weak", hebrew: "חלש", cat: "common" },
    { aramaic: "start", hebrew: "להתחיל", cat: "common" },
    { aramaic: "finish", hebrew: "לסיים", cat: "common" },
    { aramaic: "open", hebrew: "לפתוח", cat: "common" },
    { aramaic: "close", hebrew: "לסגור", cat: "common" },
    { aramaic: "buy", hebrew: "לקנות", cat: "common" },
    { aramaic: "give", hebrew: "לתת", cat: "common" },
    { aramaic: "take", hebrew: "לקחת", cat: "common" },
    { aramaic: "go", hebrew: "ללכת", cat: "common" },
    { aramaic: "come", hebrew: "לבוא", cat: "common" },
    { aramaic: "see", hebrew: "לראות", cat: "common" },
    { aramaic: "hear", hebrew: "לשמוע", cat: "common" },
    { aramaic: "speak", hebrew: "לדבר", cat: "common" },
    { aramaic: "read", hebrew: "לקרוא", cat: "common" },
    { aramaic: "write", hebrew: "לכתוב", cat: "common" },
    { aramaic: "learn", hebrew: "ללמוד", cat: "common" },
    { aramaic: "help", hebrew: "לעזור", cat: "common" },
    { aramaic: "need", hebrew: "צריך", cat: "common" },
    { aramaic: "want", hebrew: "לרצות", cat: "common" },
    { aramaic: "work", hebrew: "לעבוד", cat: "common" },
    { aramaic: "play", hebrew: "לשחק", cat: "common" },
    { aramaic: "sleep", hebrew: "לישון", cat: "common" },
    { aramaic: "eat", hebrew: "לאכול", cat: "common" },
    { aramaic: "drink", hebrew: "לשתות", cat: "common" },
    { aramaic: "water", hebrew: "מים", cat: "common" },
    { aramaic: "time", hebrew: "זמן", cat: "common" },
    { aramaic: "day", hebrew: "יום", cat: "common" },
    { aramaic: "night", hebrew: "לילה", cat: "common" },
    { aramaic: "morning", hebrew: "בוקר", cat: "common" },
    { aramaic: "evening", hebrew: "ערב", cat: "common" },
    { aramaic: "week", hebrew: "שבוע", cat: "common" },
    { aramaic: "month", hebrew: "חודש", cat: "common" },
    { aramaic: "year", hebrew: "שנה", cat: "common" },

    // בית ספר (berachot)
    { aramaic: "teacher", hebrew: "מורה", cat: "berachot" },
    { aramaic: "student", hebrew: "תלמיד", cat: "berachot" },
    { aramaic: "classroom", hebrew: "כיתה", cat: "berachot" },
    { aramaic: "lesson", hebrew: "שיעור", cat: "berachot" },
    { aramaic: "homework", hebrew: "שיעורי בית", cat: "berachot" },
    { aramaic: "test", hebrew: "מבחן", cat: "berachot" },
    { aramaic: "book", hebrew: "ספר", cat: "berachot" },
    { aramaic: "notebook", hebrew: "מחברת", cat: "berachot" },
    { aramaic: "pencil", hebrew: "עיפרון", cat: "berachot" },
    { aramaic: "pen", hebrew: "עט", cat: "berachot" },
    { aramaic: "eraser", hebrew: "מחק", cat: "berachot" },
    { aramaic: "ruler", hebrew: "סרגל", cat: "berachot" },
    { aramaic: "backpack", hebrew: "תיק", cat: "berachot" },
    { aramaic: "desk", hebrew: "שולחן", cat: "berachot" },
    { aramaic: "chair", hebrew: "כיסא", cat: "berachot" },
    { aramaic: "board", hebrew: "לוח", cat: "berachot" },
    { aramaic: "marker", hebrew: "טוש", cat: "berachot" },
    { aramaic: "paper", hebrew: "נייר", cat: "berachot" },
    { aramaic: "question", hebrew: "שאלה", cat: "berachot" },
    { aramaic: "answer", hebrew: "תשובה", cat: "berachot" },
    { aramaic: "grade", hebrew: "ציון", cat: "berachot" },
    { aramaic: "break", hebrew: "הפסקה", cat: "berachot" },
    { aramaic: "library", hebrew: "ספרייה", cat: "berachot" },
    { aramaic: "computer", hebrew: "מחשב", cat: "berachot" },
    { aramaic: "screen", hebrew: "מסך", cat: "berachot" },
    { aramaic: "keyboard", hebrew: "מקלדת", cat: "berachot" },
    { aramaic: "mouse", hebrew: "עכבר", cat: "berachot" },
    { aramaic: "internet", hebrew: "אינטרנט", cat: "berachot" },
    { aramaic: "phone", hebrew: "טלפון", cat: "berachot" },
    { aramaic: "calculator", hebrew: "מחשבון", cat: "berachot" },
    { aramaic: "schedule", hebrew: "מערכת שעות", cat: "berachot" },
    { aramaic: "project", hebrew: "פרויקט", cat: "berachot" },
    { aramaic: "presentation", hebrew: "מצגת", cat: "berachot" },
    { aramaic: "group", hebrew: "קבוצה", cat: "berachot" },
    { aramaic: "team", hebrew: "צוות", cat: "berachot" },
    { aramaic: "attendance", hebrew: "נוכחות", cat: "berachot" },
    { aramaic: "rules", hebrew: "כללים", cat: "berachot" },
    { aramaic: "permission", hebrew: "רשות", cat: "berachot" },
    { aramaic: "uniform", hebrew: "תלבושת", cat: "berachot" },
    { aramaic: "bell", hebrew: "פעמון", cat: "berachot" },
    { aramaic: "corridor", hebrew: "מסדרון", cat: "berachot" },
    { aramaic: "cafeteria", hebrew: "קפיטריה", cat: "berachot" },
    { aramaic: "playground", hebrew: "מגרש משחקים", cat: "berachot" },

    // אוכל ומטבח (bava_kamma)
    { aramaic: "apple", hebrew: "תפוח", cat: "bava_kamma" },
    { aramaic: "banana", hebrew: "בננה", cat: "bava_kamma" },
    { aramaic: "orange", hebrew: "תפוז", cat: "bava_kamma" },
    { aramaic: "grape", hebrew: "ענב", cat: "bava_kamma" },
    { aramaic: "strawberry", hebrew: "תות", cat: "bava_kamma" },
    { aramaic: "bread", hebrew: "לחם", cat: "bava_kamma" },
    { aramaic: "cheese", hebrew: "גבינה", cat: "bava_kamma" },
    { aramaic: "milk", hebrew: "חלב", cat: "bava_kamma" },
    { aramaic: "egg", hebrew: "ביצה", cat: "bava_kamma" },
    { aramaic: "rice", hebrew: "אורז", cat: "bava_kamma" },
    { aramaic: "pasta", hebrew: "פסטה", cat: "bava_kamma" },
    { aramaic: "soup", hebrew: "מרק", cat: "bava_kamma" },
    { aramaic: "chicken", hebrew: "עוף", cat: "bava_kamma" },
    { aramaic: "fish", hebrew: "דג", cat: "bava_kamma" },
    { aramaic: "meat", hebrew: "בשר", cat: "bava_kamma" },
    { aramaic: "salad", hebrew: "סלט", cat: "bava_kamma" },
    { aramaic: "sugar", hebrew: "סוכר", cat: "bava_kamma" },
    { aramaic: "salt", hebrew: "מלח", cat: "bava_kamma" },
    { aramaic: "pepper", hebrew: "פלפל", cat: "bava_kamma" },
    { aramaic: "oil", hebrew: "שמן", cat: "bava_kamma" },
    { aramaic: "butter", hebrew: "חמאה", cat: "bava_kamma" },
    { aramaic: "honey", hebrew: "דבש", cat: "bava_kamma" },
    { aramaic: "chocolate", hebrew: "שוקולד", cat: "bava_kamma" },
    { aramaic: "coffee", hebrew: "קפה", cat: "bava_kamma" },
    { aramaic: "tea", hebrew: "תה", cat: "bava_kamma" },
    { aramaic: "juice", hebrew: "מיץ", cat: "bava_kamma" },
    { aramaic: "breakfast", hebrew: "ארוחת בוקר", cat: "bava_kamma" },
    { aramaic: "lunch", hebrew: "ארוחת צהריים", cat: "bava_kamma" },
    { aramaic: "dinner", hebrew: "ארוחת ערב", cat: "bava_kamma" },
    { aramaic: "kitchen", hebrew: "מטבח", cat: "bava_kamma" },
    { aramaic: "plate", hebrew: "צלחת", cat: "bava_kamma" },
    { aramaic: "cup", hebrew: "כוס", cat: "bava_kamma" },
    { aramaic: "spoon", hebrew: "כף", cat: "bava_kamma" },
    { aramaic: "fork", hebrew: "מזלג", cat: "bava_kamma" },
    { aramaic: "knife", hebrew: "סכין", cat: "bava_kamma" },
    { aramaic: "fridge", hebrew: "מקרר", cat: "bava_kamma" },
    { aramaic: "oven", hebrew: "תנור", cat: "bava_kamma" },
    { aramaic: "stove", hebrew: "כיריים", cat: "bava_kamma" },
    { aramaic: "sink", hebrew: "כיור", cat: "bava_kamma" },
    { aramaic: "pot", hebrew: "סיר", cat: "bava_kamma" },
    { aramaic: "pan", hebrew: "מחבת", cat: "bava_kamma" },
    { aramaic: "recipe", hebrew: "מתכון", cat: "bava_kamma" },
    { aramaic: "taste", hebrew: "טעם", cat: "bava_kamma" },
    { aramaic: "sweet", hebrew: "מתוק", cat: "bava_kamma" },
    { aramaic: "sour", hebrew: "חמוץ", cat: "bava_kamma" },
    { aramaic: "spicy", hebrew: "חריף", cat: "bava_kamma" },

    // כיתה ז' (grade_7)
    { aramaic: "accept", hebrew: "לקבל", cat: "grade_7" },
    { aramaic: "adventure", hebrew: "הרפתקה", cat: "grade_7" },
    { aramaic: "ancient", hebrew: "עתיק", cat: "grade_7" },
    { aramaic: "avoid", hebrew: "להימנע", cat: "grade_7" },
    { aramaic: "behave", hebrew: "להתנהג", cat: "grade_7" },
    { aramaic: "brave", hebrew: "אמיץ", cat: "grade_7" },
    { aramaic: "calm", hebrew: "רגוע", cat: "grade_7" },
    { aramaic: "celebrate", hebrew: "לחגוג", cat: "grade_7" },
    { aramaic: "character", hebrew: "דמות", cat: "grade_7" },
    { aramaic: "clever", hebrew: "פיקח", cat: "grade_7" },
    { aramaic: "coast", hebrew: "חוף", cat: "grade_7" },
    { aramaic: "comfortable", hebrew: "נוח", cat: "grade_7" },
    { aramaic: "compare", hebrew: "להשוות", cat: "grade_7" },
    { aramaic: "contain", hebrew: "להכיל", cat: "grade_7" },
    { aramaic: "continent", hebrew: "יבשת", cat: "grade_7" },
    { aramaic: "creative", hebrew: "יצירתי", cat: "grade_7" },
    { aramaic: "crowd", hebrew: "המון", cat: "grade_7" },
    { aramaic: "culture", hebrew: "תרבות", cat: "grade_7" },
    { aramaic: "curious", hebrew: "סקרן", cat: "grade_7" },
    { aramaic: "danger", hebrew: "סכנה", cat: "grade_7" },
    { aramaic: "decide", hebrew: "להחליט", cat: "grade_7" },
    { aramaic: "describe", hebrew: "לתאר", cat: "grade_7" },
    { aramaic: "disappointed", hebrew: "מאוכזב", cat: "grade_7" },
    { aramaic: "discover", hebrew: "לגלות", cat: "grade_7" },
    { aramaic: "distance", hebrew: "מרחק", cat: "grade_7" },
    { aramaic: "education", hebrew: "חינוך", cat: "grade_7" },
    { aramaic: "encourage", hebrew: "לעודד", cat: "grade_7" },
    { aramaic: "energy", hebrew: "אנרגיה", cat: "grade_7" },
    { aramaic: "escape", hebrew: "לברוח", cat: "grade_7" },
    { aramaic: "event", hebrew: "אירוע", cat: "grade_7" },
    { aramaic: "exactly", hebrew: "בדיוק", cat: "grade_7" },
    { aramaic: "exciting", hebrew: "מרגש", cat: "grade_7" },
    { aramaic: "expect", hebrew: "לצפות", cat: "grade_7" },
    { aramaic: "explore", hebrew: "לחקור", cat: "grade_7" },
    { aramaic: "fact", hebrew: "עובדה", cat: "grade_7" },
    { aramaic: "famous", hebrew: "מפורסם", cat: "grade_7" },
    { aramaic: "favorite", hebrew: "מועדף", cat: "grade_7" },
    { aramaic: "festival", hebrew: "פסטיבל", cat: "grade_7" },
    { aramaic: "finally", hebrew: "לבסוף", cat: "grade_7" },
    { aramaic: "flight", hebrew: "טיסה", cat: "grade_7" },
    { aramaic: "forest", hebrew: "יער", cat: "grade_7" },
    { aramaic: "frighten", hebrew: "להפחיד", cat: "grade_7" },
    { aramaic: "future", hebrew: "עתיד", cat: "grade_7" },
    { aramaic: "general", hebrew: "כללי", cat: "grade_7" },
    { aramaic: "generous", hebrew: "נדיב", cat: "grade_7" },
    { aramaic: "habit", hebrew: "הרגל", cat: "grade_7" },
    { aramaic: "health", hebrew: "בריאות", cat: "grade_7" },
    { aramaic: "history", hebrew: "היסטוריה", cat: "grade_7" },
    { aramaic: "huge", hebrew: "ענק", cat: "grade_7" },
    { aramaic: "imagine", hebrew: "לדמיין", cat: "grade_7" },
    { aramaic: "improve", hebrew: "לשפר", cat: "grade_7" },
    { aramaic: "include", hebrew: "לכלול", cat: "grade_7" },
    { aramaic: "invention", hebrew: "המצאה", cat: "grade_7" },
    { aramaic: "island", hebrew: "אי", cat: "grade_7" },
    { aramaic: "journey", hebrew: "מסע", cat: "grade_7" },
    { aramaic: "knowledge", hebrew: "ידע", cat: "grade_7" },
    { aramaic: "language", hebrew: "שפה", cat: "grade_7" },
    { aramaic: "opinion", hebrew: "דעה", cat: "grade_7" },
    { aramaic: "protect", hebrew: "להגן", cat: "grade_7" },
    { aramaic: "realize", hebrew: "להבין", cat: "grade_7" },

    // כיתה ח' (grade_8)
    { aramaic: "achieve", hebrew: "להשיג", cat: "grade_8" },
    { aramaic: "admit", hebrew: "להודות", cat: "grade_8" },
    { aramaic: "advantage", hebrew: "יתרון", cat: "grade_8" },
    { aramaic: "affect", hebrew: "להשפיע", cat: "grade_8" },
    { aramaic: "afford", hebrew: "להרשות", cat: "grade_8" },
    { aramaic: "alternative", hebrew: "חלופה", cat: "grade_8" },
    { aramaic: "although", hebrew: "למרות", cat: "grade_8" },
    { aramaic: "amount", hebrew: "כמות", cat: "grade_8" },
    { aramaic: "apologize", hebrew: "להתנצל", cat: "grade_8" },
    { aramaic: "appearance", hebrew: "מראה", cat: "grade_8" },
    { aramaic: "appreciate", hebrew: "להעריך", cat: "grade_8" },
    { aramaic: "attitude", hebrew: "גישה", cat: "grade_8" },
    { aramaic: "average", hebrew: "ממוצע", cat: "grade_8" },
    { aramaic: "benefit", hebrew: "תועלת", cat: "grade_8" },
    { aramaic: "blame", hebrew: "להאשים", cat: "grade_8" },
    { aramaic: "career", hebrew: "קריירה", cat: "grade_8" },
    { aramaic: "ceremony", hebrew: "טקס", cat: "grade_8" },
    { aramaic: "certain", hebrew: "בטוח", cat: "grade_8" },
    { aramaic: "challenge", hebrew: "אתגר", cat: "grade_8" },
    { aramaic: "choice", hebrew: "בחירה", cat: "grade_8" },
    { aramaic: "citizen", hebrew: "אזרח", cat: "grade_8" },
    { aramaic: "claim", hebrew: "לטעון", cat: "grade_8" },
    { aramaic: "climate", hebrew: "אקלים", cat: "grade_8" },
    { aramaic: "collection", hebrew: "אוסף", cat: "grade_8" },
    { aramaic: "combine", hebrew: "לשלב", cat: "grade_8" },
    { aramaic: "comment", hebrew: "להעיר", cat: "grade_8" },
    { aramaic: "community", hebrew: "קהילה", cat: "grade_8" },
    { aramaic: "complain", hebrew: "להתלונן", cat: "grade_8" },
    { aramaic: "complicated", hebrew: "מסובך", cat: "grade_8" },
    { aramaic: "concentrate", hebrew: "להתרכז", cat: "grade_8" },
    { aramaic: "conclusion", hebrew: "מסקנה", cat: "grade_8" },
    { aramaic: "confident", hebrew: "בטוח", cat: "grade_8" },
    { aramaic: "connect", hebrew: "לחבר", cat: "grade_8" },
    { aramaic: "consequence", hebrew: "תוצאה", cat: "grade_8" },
    { aramaic: "consider", hebrew: "לשקול", cat: "grade_8" },
    { aramaic: "consist", hebrew: "מורכב", cat: "grade_8" },
    { aramaic: "constantly", hebrew: "בקביעות", cat: "grade_8" },
    { aramaic: "construction", hebrew: "בנייה", cat: "grade_8" },
    { aramaic: "contact", hebrew: "מגע", cat: "grade_8" },
    { aramaic: "convenient", hebrew: "נגיש", cat: "grade_8" },
    { aramaic: "conversation", hebrew: "שיחה", cat: "grade_8" },
    { aramaic: "convince", hebrew: "לשכנע", cat: "grade_8" },
    { aramaic: "current", hebrew: "נוכחי", cat: "grade_8" },
    { aramaic: "damage", hebrew: "נזק", cat: "grade_8" },
    { aramaic: "decade", hebrew: "עשור", cat: "grade_8" },
    { aramaic: "decrease", hebrew: "להפחית", cat: "grade_8" },
    { aramaic: "define", hebrew: "להגדיר", cat: "grade_8" },
    { aramaic: "definitely", hebrew: "בהחלט", cat: "grade_8" },
    { aramaic: "definition", hebrew: "הגדרה", cat: "grade_8" },
    { aramaic: "demand", hebrew: "לדרוש", cat: "grade_8" },
    { aramaic: "deny", hebrew: "להכחיש", cat: "grade_8" },
    { aramaic: "depend", hebrew: "להסתמך", cat: "grade_8" },
    { aramaic: "despite", hebrew: "למרות", cat: "grade_8" },
    { aramaic: "detail", hebrew: "פרט", cat: "grade_8" },
    { aramaic: "develop", hebrew: "לפתח", cat: "grade_8" },
    { aramaic: "difference", hebrew: "הבדל", cat: "grade_8" },
    { aramaic: "difficulty", hebrew: "קושי", cat: "grade_8" },
    { aramaic: "direction", hebrew: "כיוון", cat: "grade_8" },
    { aramaic: "discussion", hebrew: "דיון", cat: "grade_8" },
    { aramaic: "disease", hebrew: "מחלה", cat: "grade_8" },

    // כיתה ט' (grade_9)
    { aramaic: "ability", hebrew: "יכולת", cat: "grade_9" },
    { aramaic: "absolute", hebrew: "מוחלט", cat: "grade_9" },
    { aramaic: "access", hebrew: "גישה", cat: "grade_9" },
    { aramaic: "accompany", hebrew: "ללוות", cat: "grade_9" },
    { aramaic: "according to", hebrew: "לפי", cat: "grade_9" },
    { aramaic: "account", hebrew: "חשבון", cat: "grade_9" },
    { aramaic: "accurate", hebrew: "מדויק", cat: "grade_9" },
    { aramaic: "accuse", hebrew: "להאשים", cat: "grade_9" },
    { aramaic: "acquire", hebrew: "לרכוש", cat: "grade_9" },
    { aramaic: "action", hebrew: "פעולה", cat: "grade_9" },
    { aramaic: "adapt", hebrew: "להסתגל", cat: "grade_9" },
    { aramaic: "addition", hebrew: "תוספת", cat: "grade_9" },
    { aramaic: "additional", hebrew: "נוסף", cat: "grade_9" },
    { aramaic: "address", hebrew: "כתובת", cat: "grade_9" },
    { aramaic: "administration", hebrew: "מנהל", cat: "grade_9" },
    { aramaic: "adopt", hebrew: "לאמץ", cat: "grade_9" },
    { aramaic: "advance", hebrew: "להתקדם", cat: "grade_9" },
    { aramaic: "advertise", hebrew: "לפרסם", cat: "grade_9" },
    { aramaic: "agency", hebrew: "סוכנות", cat: "grade_9" },
    { aramaic: "aggressive", hebrew: "תוקפני", cat: "grade_9" },
    { aramaic: "agreement", hebrew: "הסכם", cat: "grade_9" },
    { aramaic: "agriculture", hebrew: "חקלאות", cat: "grade_9" },
    { aramaic: "aid", hebrew: "סיוע", cat: "grade_9" },
    { aramaic: "aim", hebrew: "מטרה", cat: "grade_9" },
    { aramaic: "aircraft", hebrew: "מטוס", cat: "grade_9" },
    { aramaic: "alarm", hebrew: "אזעקה", cat: "grade_9" },
    { aramaic: "allow", hebrew: "לאפשר", cat: "grade_9" },
    { aramaic: "ally", hebrew: "שותף", cat: "grade_9" },
    { aramaic: "alongside", hebrew: "לצד", cat: "grade_9" },
    { aramaic: "alter", hebrew: "לשנות", cat: "grade_9" },
    { aramaic: "ambition", hebrew: "שאיפה", cat: "grade_9" },
    { aramaic: "analysis", hebrew: "ניתוח", cat: "grade_9" },
    { aramaic: "announcement", hebrew: "הודעה", cat: "grade_9" },
    { aramaic: "annoy", hebrew: "להציק", cat: "grade_9" },
    { aramaic: "annual", hebrew: "שנתי", cat: "grade_9" },
    { aramaic: "anticipate", hebrew: "לצפות", cat: "grade_9" },
    { aramaic: "anxiety", hebrew: "חרדה", cat: "grade_9" },
    { aramaic: "anxious", hebrew: "חרד", cat: "grade_9" },
    { aramaic: "apparent", hebrew: "גלוי", cat: "grade_9" },
    { aramaic: "appeal", hebrew: "ערעור", cat: "grade_9" },
    { aramaic: "appear", hebrew: "להופיע", cat: "grade_9" },
    { aramaic: "application", hebrew: "יישום", cat: "grade_9" },
    { aramaic: "apply", hebrew: "ליישם", cat: "grade_9" },
    { aramaic: "appoint", hebrew: "למנות", cat: "grade_9" },
    { aramaic: "appointment", hebrew: "פגישה", cat: "grade_9" },
    { aramaic: "approach", hebrew: "לגשת", cat: "grade_9" },
    { aramaic: "appropriate", hebrew: "מתאים", cat: "grade_9" },
    { aramaic: "argument", hebrew: "ויכוח", cat: "grade_9" },
    { aramaic: "arrangement", hebrew: "סידור", cat: "grade_9" },
    { aramaic: "artificial", hebrew: "מלאכותי", cat: "grade_9" },
    { aramaic: "aspect", hebrew: "היבט", cat: "grade_9" },
    { aramaic: "assembly", hebrew: "אסיפה", cat: "grade_9" },
    { aramaic: "assess", hebrew: "להעריך", cat: "grade_9" },
    { aramaic: "associate", hebrew: "לקשר", cat: "grade_9" },
    { aramaic: "assume", hebrew: "להניח", cat: "grade_9" },
    { aramaic: "attempt", hebrew: "לנסות", cat: "grade_9" },
    { aramaic: "attend", hebrew: "להשתתף", cat: "grade_9" },
    { aramaic: "attitude", hebrew: "עמדה", cat: "grade_9" },
    { aramaic: "attract", hebrew: "למשוך", cat: "grade_9" },
    { aramaic: "available", hebrew: "זמין", cat: "grade_9" }
];
