
import { Word, ShopItem, Achievement, Sugia } from './types';

export const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycby2j8DTeve82fE_a_4j1_Py3SZj02JlrroBWzONc_Mtk1X7VVIbUHpKpdtvWgjqS15l4w/exec';

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'zurba', title: 'מאסטר קומבו', desc: 'רצף (Combo) של 10 פגיעות נכונות ברצף', icon: '🎯' },
  { id: 'sinai', title: 'ריצה מושלמת', desc: 'ניצחון על בוס בלי לאבד אף חיים', icon: '⭐' },
  { id: 'gamir', title: 'אספן ציוד', desc: 'רכישת כל השדרוגים והסקינים בחנות', icon: '🧰' }
];

export const SUGIOT: Sugia[] = [
  { id: 0, title: 'יחידה 1: חימום', location: 'nehardea', description: 'חימום קצר – האויבים נעים בתנועה גלית.', requiredLevel: 1, modifier: 'wave' },
  { id: 1, title: 'יחידה 2: פוקוס', location: 'nehardea', description: 'יותר עומס – צפיפות אויבים גדולה יותר.', requiredLevel: 8, modifier: 'density' },
  { id: 2, title: 'יחידה 3: מטר אותיות', location: 'sura', description: 'זהירות! אותיות נופלות מהשמיים.', requiredLevel: 15, modifier: 'hazards' },
  { id: 3, title: 'יחידה 4: מהירות', location: 'sura', description: 'האויבים מאיצים לקראתך – צריך תגובה מהירה.', requiredLevel: 22, modifier: 'accelerate' },
  { id: 4, title: 'יחידה 5: מיקרו-מילים', location: 'pumbedita', description: 'מילים קטנות ומהירות במיוחד.', requiredLevel: 29, modifier: 'sharpness' },
  { id: 5, title: 'יחידה 6: רוח צד', location: 'pumbedita', description: 'רוח צדדית משפיעה על תנועת המטוס.', requiredLevel: 36, modifier: 'drift' },
  { id: 6, title: 'יחידה 7: הבהוב', location: 'mahoza', description: 'האויבים מהבהבים ונעלמים מהעין.', requiredLevel: 43, modifier: 'blink' },
  { id: 7, title: 'יחידה 8: כאוס', location: 'mahoza', description: 'מסלולים קופצניים ולא צפויים.', requiredLevel: 50, modifier: 'chaos' },
  { id: 8, title: 'יחידה 9: חושך', location: 'matamehasia', description: 'הראות מוגבלת לאזור הקרוב למטוס.', requiredLevel: 57, modifier: 'darkness' },
  { id: 9, title: 'יחידה 10: מערבולת', location: 'matamehasia', description: 'האויבים נמשכים למרכז המסך.', requiredLevel: 64, modifier: 'vortex' },
  { id: 10, title: 'יחידה 11: סערה', location: 'beiradelvat', description: 'רוחות חזקות ומכשולים רבים.', requiredLevel: 71, modifier: 'storm' },
  { id: 11, title: 'יחידה 12: מבחן סופי', location: 'beiradelvat', description: 'שילוב כל האתגרים לקרב האחרון.', requiredLevel: 78, modifier: 'final' }
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'skin_default', name: 'מטוס רגיל', type: 'skin', price: 0, desc: 'מטוס קרב סטנדרטי שיורה כדורי אנרגיה', icon: '✈️' },
  { id: 'skin_gold', name: 'סילון זהב', type: 'skin', price: 800, desc: 'מטוס יוקרתי שיורה קרן אור עוצמתית (דרוש מאסטר קומבו)', icon: '☀️', requiredAchievement: 'zurba' },
  { id: 'skin_butzina', name: 'לייזר סגול', type: 'skin', price: 1000, desc: 'מטוס בצבע סגול שיורה קווי לייזר', icon: '🟣' },
  { id: 'skin_torah', name: 'תותח אש', type: 'skin', price: 1500, desc: 'מטוס עם ירי אש עוצמתי (דרושה ריצה מושלמת)', icon: '🔥', requiredAchievement: 'sinai' },
  { id: 'skin_choshen', name: 'קשת חשמל', type: 'skin', price: 2000, desc: 'מבנה עוצמתי שיורה קשתות חשמל', icon: '⚡' },
  { id: 'upgrade_bomb', name: 'פצצת איפוס', type: 'consumable', price: 250, desc: 'מנקה את כל המסך מאויבים', icon: '💣' },
  { id: 'item_shield', name: 'מגן אנרגיה', type: 'consumable', price: 300, desc: 'מגן מפני פגיעה אחת (לחץ S) - עד 3', icon: '🛡️' },
  { id: 'item_freeze', name: 'האטת זמן', type: 'consumable', price: 400, desc: 'מאט את כל האויבים לזמן ממושך (לחץ D) - עד 3', icon: '⏳' }
];

export const DICTIONARY: Word[] = [
    // בסיס (Common)
    { aramaic: "hello", hebrew: "שלום", cat: "common" },
    { aramaic: "goodbye", hebrew: "להתראות", cat: "common" },
    { aramaic: "please", hebrew: "בבקשה", cat: "common" },
    { aramaic: "thank you", hebrew: "תודה", cat: "common" },
    { aramaic: "sorry", hebrew: "סליחה", cat: "common" },
    { aramaic: "yes", hebrew: "כן", cat: "common" },
    { aramaic: "no", hebrew: "לא", cat: "common" },
    { aramaic: "maybe", hebrew: "אולי", cat: "common" },
    { aramaic: "now", hebrew: "עכשיו", cat: "common" },
    { aramaic: "later", hebrew: "אחר כך", cat: "common" },
    { aramaic: "today", hebrew: "היום", cat: "common" },
    { aramaic: "tomorrow", hebrew: "מחר", cat: "common" },
    { aramaic: "yesterday", hebrew: "אתמול", cat: "common" },
    { aramaic: "always", hebrew: "תמיד", cat: "common" },
    { aramaic: "never", hebrew: "אף פעם", cat: "common" },
    { aramaic: "sometimes", hebrew: "לפעמים", cat: "common" },
    { aramaic: "again", hebrew: "שוב", cat: "common" },
    { aramaic: "because", hebrew: "בגלל", cat: "common" },
    { aramaic: "but", hebrew: "אבל", cat: "common" },
    { aramaic: "and", hebrew: "וגם", cat: "common" },
    { aramaic: "or", hebrew: "או", cat: "common" },
    { aramaic: "who", hebrew: "מי", cat: "common" },
    { aramaic: "what", hebrew: "מה", cat: "common" },
    { aramaic: "where", hebrew: "איפה", cat: "common" },
    { aramaic: "when", hebrew: "מתי", cat: "common" },
    { aramaic: "why", hebrew: "למה", cat: "common" },
    { aramaic: "how", hebrew: "איך", cat: "common" },
    { aramaic: "big", hebrew: "גדול", cat: "common" },
    { aramaic: "small", hebrew: "קטן", cat: "common" },
    { aramaic: "good", hebrew: "טוב", cat: "common" },
    { aramaic: "bad", hebrew: "רע", cat: "common" },
    { aramaic: "new", hebrew: "חדש", cat: "common" },
    { aramaic: "old", hebrew: "ישן", cat: "common" },
    { aramaic: "hot", hebrew: "חם", cat: "common" },
    { aramaic: "cold", hebrew: "קר", cat: "common" },
    { aramaic: "fast", hebrew: "מהיר", cat: "common" },
    { aramaic: "slow", hebrew: "איטי", cat: "common" },
    { aramaic: "easy", hebrew: "קל", cat: "common" },
    { aramaic: "hard", hebrew: "קשה", cat: "common" },
    { aramaic: "happy", hebrew: "שמח", cat: "common" },
    { aramaic: "sad", hebrew: "עצוב", cat: "common" },
    { aramaic: "strong", hebrew: "חזק", cat: "common" },
    { aramaic: "weak", hebrew: "חלש", cat: "common" },
    { aramaic: "start", hebrew: "להתחיל", cat: "common" },
    { aramaic: "finish", hebrew: "לסיים", cat: "common" },
    { aramaic: "open", hebrew: "לפתוח", cat: "common" },
    { aramaic: "close", hebrew: "לסגור", cat: "common" },
    { aramaic: "buy", hebrew: "לקנות", cat: "common" },
    { aramaic: "give", hebrew: "לתת", cat: "common" },
    { aramaic: "take", hebrew: "לקחת", cat: "common" },
    { aramaic: "go", hebrew: "ללכת", cat: "common" },
    { aramaic: "come", hebrew: "לבוא", cat: "common" },
    { aramaic: "see", hebrew: "לראות", cat: "common" },
    { aramaic: "hear", hebrew: "לשמוע", cat: "common" },
    { aramaic: "speak", hebrew: "לדבר", cat: "common" },
    { aramaic: "read", hebrew: "לקרוא", cat: "common" },
    { aramaic: "write", hebrew: "לכתוב", cat: "common" },
    { aramaic: "learn", hebrew: "ללמוד", cat: "common" },
    { aramaic: "help", hebrew: "לעזור", cat: "common" },
    { aramaic: "need", hebrew: "צריך", cat: "common" },
    { aramaic: "want", hebrew: "לרצות", cat: "common" },
    { aramaic: "work", hebrew: "לעבוד", cat: "common" },
    { aramaic: "play", hebrew: "לשחק", cat: "common" },
    { aramaic: "sleep", hebrew: "לישון", cat: "common" },
    { aramaic: "eat", hebrew: "לאכול", cat: "common" },
    { aramaic: "drink", hebrew: "לשתות", cat: "common" },
    { aramaic: "water", hebrew: "מים", cat: "common" },
    { aramaic: "time", hebrew: "זמן", cat: "common" },
    { aramaic: "day", hebrew: "יום", cat: "common" },
    { aramaic: "night", hebrew: "לילה", cat: "common" },
    { aramaic: "morning", hebrew: "בוקר", cat: "common" },
    { aramaic: "evening", hebrew: "ערב", cat: "common" },
    { aramaic: "week", hebrew: "שבוע", cat: "common" },
    { aramaic: "month", hebrew: "חודש", cat: "common" },
    { aramaic: "year", hebrew: "שנה", cat: "common" },

    // בית ספר (berachot)
    { aramaic: "teacher", hebrew: "מורה", cat: "berachot" },
    { aramaic: "student", hebrew: "תלמיד", cat: "berachot" },
    { aramaic: "classroom", hebrew: "כיתה", cat: "berachot" },
    { aramaic: "lesson", hebrew: "שיעור", cat: "berachot" },
    { aramaic: "homework", hebrew: "שיעורי בית", cat: "berachot" },
    { aramaic: "test", hebrew: "מבחן", cat: "berachot" },
    { aramaic: "book", hebrew: "ספר", cat: "berachot" },
    { aramaic: "notebook", hebrew: "מחברת", cat: "berachot" },
    { aramaic: "pencil", hebrew: "עיפרון", cat: "berachot" },
    { aramaic: "pen", hebrew: "עט", cat: "berachot" },
    { aramaic: "eraser", hebrew: "מחק", cat: "berachot" },
    { aramaic: "ruler", hebrew: "סרגל", cat: "berachot" },
    { aramaic: "backpack", hebrew: "תיק", cat: "berachot" },
    { aramaic: "desk", hebrew: "שולחן", cat: "berachot" },
    { aramaic: "chair", hebrew: "כיסא", cat: "berachot" },
    { aramaic: "board", hebrew: "לוח", cat: "berachot" },
    { aramaic: "marker", hebrew: "טוש", cat: "berachot" },
    { aramaic: "paper", hebrew: "נייר", cat: "berachot" },
    { aramaic: "question", hebrew: "שאלה", cat: "berachot" },
    { aramaic: "answer", hebrew: "תשובה", cat: "berachot" },
    { aramaic: "grade", hebrew: "ציון", cat: "berachot" },
    { aramaic: "break", hebrew: "הפסקה", cat: "berachot" },
    { aramaic: "library", hebrew: "ספרייה", cat: "berachot" },
    { aramaic: "computer", hebrew: "מחשב", cat: "berachot" },
    { aramaic: "screen", hebrew: "מסך", cat: "berachot" },
    { aramaic: "keyboard", hebrew: "מקלדת", cat: "berachot" },
    { aramaic: "mouse", hebrew: "עכבר", cat: "berachot" },
    { aramaic: "internet", hebrew: "אינטרנט", cat: "berachot" },
    { aramaic: "phone", hebrew: "טלפון", cat: "berachot" },
    { aramaic: "calculator", hebrew: "מחשבון", cat: "berachot" },
    { aramaic: "schedule", hebrew: "מערכת שעות", cat: "berachot" },
    { aramaic: "project", hebrew: "פרויקט", cat: "berachot" },
    { aramaic: "presentation", hebrew: "מצגת", cat: "berachot" },
    { aramaic: "group", hebrew: "קבוצה", cat: "berachot" },
    { aramaic: "team", hebrew: "צוות", cat: "berachot" },
    { aramaic: "attendance", hebrew: "נוכחות", cat: "berachot" },
    { aramaic: "rules", hebrew: "כללים", cat: "berachot" },
    { aramaic: "permission", hebrew: "רשות", cat: "berachot" },
    { aramaic: "uniform", hebrew: "תלבושת", cat: "berachot" },
    { aramaic: "bell", hebrew: "פעמון", cat: "berachot" },
    { aramaic: "corridor", hebrew: "מסדרון", cat: "berachot" },
    { aramaic: "cafeteria", hebrew: "קפיטריה", cat: "berachot" },
    { aramaic: "playground", hebrew: "מגרש משחקים", cat: "berachot" },

    // אוכל ומטבח (bava_kamma)
    { aramaic: "apple", hebrew: "תפוח", cat: "bava_kamma" },
    { aramaic: "banana", hebrew: "בננה", cat: "bava_kamma" },
    { aramaic: "orange", hebrew: "תפוז", cat: "bava_kamma" },
    { aramaic: "grape", hebrew: "ענב", cat: "bava_kamma" },
    { aramaic: "strawberry", hebrew: "תות", cat: "bava_kamma" },
    { aramaic: "bread", hebrew: "לחם", cat: "bava_kamma" },
    { aramaic: "cheese", hebrew: "גבינה", cat: "bava_kamma" },
    { aramaic: "milk", hebrew: "חלב", cat: "bava_kamma" },
    { aramaic: "egg", hebrew: "ביצה", cat: "bava_kamma" },
    { aramaic: "rice", hebrew: "אורז", cat: "bava_kamma" },
    { aramaic: "pasta", hebrew: "פסטה", cat: "bava_kamma" },
    { aramaic: "soup", hebrew: "מרק", cat: "bava_kamma" },
    { aramaic: "chicken", hebrew: "עוף", cat: "bava_kamma" },
    { aramaic: "fish", hebrew: "דג", cat: "bava_kamma" },
    { aramaic: "meat", hebrew: "בשר", cat: "bava_kamma" },
    { aramaic: "salad", hebrew: "סלט", cat: "bava_kamma" },
    { aramaic: "sugar", hebrew: "סוכר", cat: "bava_kamma" },
    { aramaic: "salt", hebrew: "מלח", cat: "bava_kamma" },
    { aramaic: "pepper", hebrew: "פלפל", cat: "bava_kamma" },
    { aramaic: "oil", hebrew: "שמן", cat: "bava_kamma" },
    { aramaic: "butter", hebrew: "חמאה", cat: "bava_kamma" },
    { aramaic: "honey", hebrew: "דבש", cat: "bava_kamma" },
    { aramaic: "chocolate", hebrew: "שוקולד", cat: "bava_kamma" },
    { aramaic: "coffee", hebrew: "קפה", cat: "bava_kamma" },
    { aramaic: "tea", hebrew: "תה", cat: "bava_kamma" },
    { aramaic: "juice", hebrew: "מיץ", cat: "bava_kamma" },
    { aramaic: "breakfast", hebrew: "ארוחת בוקר", cat: "bava_kamma" },
    { aramaic: "lunch", hebrew: "ארוחת צהריים", cat: "bava_kamma" },
    { aramaic: "dinner", hebrew: "ארוחת ערב", cat: "bava_kamma" },
    { aramaic: "kitchen", hebrew: "מטבח", cat: "bava_kamma" },
    { aramaic: "plate", hebrew: "צלחת", cat: "bava_kamma" },
    { aramaic: "cup", hebrew: "כוס", cat: "bava_kamma" },
    { aramaic: "spoon", hebrew: "כף", cat: "bava_kamma" },
    { aramaic: "fork", hebrew: "מזלג", cat: "bava_kamma" },
    { aramaic: "knife", hebrew: "סכין", cat: "bava_kamma" },
    { aramaic: "fridge", hebrew: "מקרר", cat: "bava_kamma" },
    { aramaic: "oven", hebrew: "תנור", cat: "bava_kamma" },
    { aramaic: "stove", hebrew: "כיריים", cat: "bava_kamma" },
    { aramaic: "sink", hebrew: "כיור", cat: "bava_kamma" },
    { aramaic: "pot", hebrew: "סיר", cat: "bava_kamma" },
    { aramaic: "pan", hebrew: "מחבת", cat: "bava_kamma" },
    { aramaic: "recipe", hebrew: "מתכון", cat: "bava_kamma" },
    { aramaic: "taste", hebrew: "טעם", cat: "bava_kamma" },
    { aramaic: "sweet", hebrew: "מתוק", cat: "bava_kamma" },
    { aramaic: "sour", hebrew: "חמוץ", cat: "bava_kamma" },
    { aramaic: "spicy", hebrew: "חריף", cat: "bava_kamma" }
];
